USE HadoopClimate;
INSERT INTO Country(country, idContinent) VALUES ('Albania', 4);
INSERT INTO Country(country, idContinent) VALUES ('Austria', 4);
INSERT INTO Country(country, idContinent) VALUES ('Belarus', 4);
INSERT INTO Country(country, idContinent) VALUES ('Belgium', 4);
INSERT INTO Country(country, idContinent) VALUES ('Bosnia and Herzegovina', 4);
INSERT INTO Country(country, idContinent) VALUES ('Bulgaria', 4);
INSERT INTO Country(country, idContinent) VALUES ('Croatia', 4);
INSERT INTO Country(country, idContinent) VALUES ('Czech Republic', 4);
INSERT INTO Country(country, idContinent) VALUES ('Denmark', 4);
INSERT INTO Country(country, idContinent) VALUES ('Estonia', 4);
INSERT INTO Country(country, idContinent) VALUES ('Finland', 4);
INSERT INTO Country(country, idContinent) VALUES ('Former Yugoslav Republic of Macedonia', 4);
INSERT INTO Country(country, idContinent) VALUES ('France', 4);
INSERT INTO Country(country, idContinent) VALUES ('Germany', 4);
INSERT INTO Country(country, idContinent) VALUES ('Gibraltar', 4);
INSERT INTO Country(country, idContinent) VALUES ('Greece', 4);
INSERT INTO Country(country, idContinent) VALUES ('Hungary', 4);
INSERT INTO Country(country, idContinent) VALUES ('Iceland', 4);
INSERT INTO Country(country, idContinent) VALUES ('Ireland', 4);
INSERT INTO Country(country, idContinent) VALUES ('Italy', 4);
INSERT INTO Country(country, idContinent) VALUES ('Latvia', 4);
INSERT INTO Country(country, idContinent) VALUES ('Lithuania', 4);
INSERT INTO Country(country, idContinent) VALUES ('Luxembourg', 4);
INSERT INTO Country(country, idContinent) VALUES ('Malta', 4);
INSERT INTO Country(country, idContinent) VALUES ('Moldova', 4);
INSERT INTO Country(country, idContinent) VALUES ('Netherlands', 4);
INSERT INTO Country(country, idContinent) VALUES ('Norway', 4);
INSERT INTO Country(country, idContinent) VALUES ('Poland', 4);
INSERT INTO Country(country, idContinent) VALUES ('Portugal', 4);
INSERT INTO Country(country, idContinent) VALUES ('Romania', 4);
INSERT INTO Country(country, idContinent) VALUES ('Slovakia', 4);
INSERT INTO Country(country, idContinent) VALUES ('Slovenia', 4);
INSERT INTO Country(country, idContinent) VALUES ('Spain', 4);
INSERT INTO Country(country, idContinent) VALUES ('Sweden', 4);
INSERT INTO Country(country, idContinent) VALUES ('Switzerland', 4);
INSERT INTO Country(country, idContinent) VALUES ('Ukraine', 4);
INSERT INTO Country(country, idContinent) VALUES ('United Kingdom', 4);
INSERT INTO Country(country, idContinent) VALUES ('Yugoslavia', 4);
INSERT INTO Country(country, idContinent) VALUES ('Afghanistan', 3);
INSERT INTO Country(country, idContinent) VALUES ('Armenia', 3);
INSERT INTO Country(country, idContinent) VALUES ('Azerbaijan', 3);
INSERT INTO Country(country, idContinent) VALUES ('Bahrain', 3);
INSERT INTO Country(country, idContinent) VALUES ('Bangladesh', 3);
INSERT INTO Country(country, idContinent) VALUES ('Brunei', 3);
INSERT INTO Country(country, idContinent) VALUES ('Cambodia', 3);
INSERT INTO Country(country, idContinent) VALUES ('China', 3);
INSERT INTO Country(country, idContinent) VALUES ('Cyprus', 3);
INSERT INTO Country(country, idContinent) VALUES ('Georgia', 3);
INSERT INTO Country(country, idContinent) VALUES ('Hong Kong', 3);
INSERT INTO Country(country, idContinent) VALUES ('India', 3);
INSERT INTO Country(country, idContinent) VALUES ('Indonesia', 3);
INSERT INTO Country(country, idContinent) VALUES ('Iran', 3);
INSERT INTO Country(country, idContinent) VALUES ('Iraq', 3);
INSERT INTO Country(country, idContinent) VALUES ('Israel', 3);
INSERT INTO Country(country, idContinent) VALUES ('Japan', 3);
INSERT INTO Country(country, idContinent) VALUES ('Jordan', 3);
INSERT INTO Country(country, idContinent) VALUES ('Kazakhstan', 3);
INSERT INTO Country(country, idContinent) VALUES ('Kuwait', 3);
INSERT INTO Country(country, idContinent) VALUES ('Kyrgyzstan', 3);
INSERT INTO Country(country, idContinent) VALUES ('Laos', 3);
INSERT INTO Country(country, idContinent) VALUES ('Lebanon', 3);
INSERT INTO Country(country, idContinent) VALUES ('Macau', 3);
INSERT INTO Country(country, idContinent) VALUES ('Malaysia', 3);
INSERT INTO Country(country, idContinent) VALUES ('Maldives', 3);
INSERT INTO Country(country, idContinent) VALUES ('Mongolia', 3);
INSERT INTO Country(country, idContinent) VALUES ('Myanmar', 3);
INSERT INTO Country(country, idContinent) VALUES ('Nepal', 3);
INSERT INTO Country(country, idContinent) VALUES ('North Korea', 3);
INSERT INTO Country(country, idContinent) VALUES ('Oman', 3);
INSERT INTO Country(country, idContinent) VALUES ('Pakistan', 3);
INSERT INTO Country(country, idContinent) VALUES ('Philippines', 3);
INSERT INTO Country(country, idContinent) VALUES ('Qatar', 3);
INSERT INTO Country(country, idContinent) VALUES ('Russia', 3);
INSERT INTO Country(country, idContinent) VALUES ('Saudi Arabia', 3);
INSERT INTO Country(country, idContinent) VALUES ('Singapore', 3);
INSERT INTO Country(country, idContinent) VALUES ('South Korea', 3);
INSERT INTO Country(country, idContinent) VALUES ('Sri Lanka', 3);
INSERT INTO Country(country, idContinent) VALUES ('Syria', 3);
INSERT INTO Country(country, idContinent) VALUES ('Taiwan', 3);
INSERT INTO Country(country, idContinent) VALUES ('Tajikistan', 3);
INSERT INTO Country(country, idContinent) VALUES ('Thailand', 3);
INSERT INTO Country(country, idContinent) VALUES ('Turkey', 3);
INSERT INTO Country(country, idContinent) VALUES ('Turkmenistan', 3);
INSERT INTO Country(country, idContinent) VALUES ('United Arab Emirates', 3);
INSERT INTO Country(country, idContinent) VALUES ('Uzbekistan', 3);
INSERT INTO Country(country, idContinent) VALUES ('Vietnam', 3);
INSERT INTO Country(country, idContinent) VALUES ('Yemen', 3);
INSERT INTO Country(country, idContinent) VALUES ('Algeria', 1);
INSERT INTO Country(country, idContinent) VALUES ('Angola', 1);
INSERT INTO Country(country, idContinent) VALUES ('Benin', 1);
INSERT INTO Country(country, idContinent) VALUES ('Botswana', 1);
INSERT INTO Country(country, idContinent) VALUES ('British Indian Ocean Territory', 1);
INSERT INTO Country(country, idContinent) VALUES ('Burkina Faso', 1);
INSERT INTO Country(country, idContinent) VALUES ('Cameroon', 1);
INSERT INTO Country(country, idContinent) VALUES ('Cape Verde', 1);
INSERT INTO Country(country, idContinent) VALUES ('Central African Republic', 1);
INSERT INTO Country(country, idContinent) VALUES ('Chad', 1);
INSERT INTO Country(country, idContinent) VALUES ('Comoros', 1);
INSERT INTO Country(country, idContinent) VALUES ('Congo', 1);
INSERT INTO Country(country, idContinent) VALUES ('Côte dIvoire', 1);
INSERT INTO Country(country, idContinent) VALUES ('Democratic Republic of the Congo', 1);
INSERT INTO Country(country, idContinent) VALUES ('Djibouti', 1);
INSERT INTO Country(country, idContinent) VALUES ('Egypt', 1);
INSERT INTO Country(country, idContinent) VALUES ('Equatorial Guinea', 1);
INSERT INTO Country(country, idContinent) VALUES ('Ethiopia', 1);
INSERT INTO Country(country, idContinent) VALUES ('Gabon', 1);
INSERT INTO Country(country, idContinent) VALUES ('Ghana', 1);
INSERT INTO Country(country, idContinent) VALUES ('Guinea', 1);
INSERT INTO Country(country, idContinent) VALUES ('Guinea-Bissau', 1);
INSERT INTO Country(country, idContinent) VALUES ('Kenya', 1);
INSERT INTO Country(country, idContinent) VALUES ('Liberia', 1);
INSERT INTO Country(country, idContinent) VALUES ('Libya', 1);
INSERT INTO Country(country, idContinent) VALUES ('Madagascar', 1);
INSERT INTO Country(country, idContinent) VALUES ('Mali', 1);
INSERT INTO Country(country, idContinent) VALUES ('Mauritania', 1);
INSERT INTO Country(country, idContinent) VALUES ('Mauritius', 1);
INSERT INTO Country(country, idContinent) VALUES ('Morocco', 1);
INSERT INTO Country(country, idContinent) VALUES ('Mozambique', 1);
INSERT INTO Country(country, idContinent) VALUES ('Namibia', 1);
INSERT INTO Country(country, idContinent) VALUES ('Niger', 1);
INSERT INTO Country(country, idContinent) VALUES ('Nigeria', 1);
INSERT INTO Country(country, idContinent) VALUES ('Réunion', 1);
INSERT INTO Country(country, idContinent) VALUES ('Rwanda', 1);
INSERT INTO Country(country, idContinent) VALUES ('Saint Helena', 1);
INSERT INTO Country(country, idContinent) VALUES ('São Tomé and Príncipe', 1);
INSERT INTO Country(country, idContinent) VALUES ('Senegal', 1);
INSERT INTO Country(country, idContinent) VALUES ('Seychelles', 1);
INSERT INTO Country(country, idContinent) VALUES ('South Africa', 1);
INSERT INTO Country(country, idContinent) VALUES ('Sudan', 1);
INSERT INTO Country(country, idContinent) VALUES ('Swaziland', 1);
INSERT INTO Country(country, idContinent) VALUES ('Tanzania', 1);
INSERT INTO Country(country, idContinent) VALUES ('The Gambia', 1);
INSERT INTO Country(country, idContinent) VALUES ('Togo', 1);
INSERT INTO Country(country, idContinent) VALUES ('Tunisia', 1);
INSERT INTO Country(country, idContinent) VALUES ('Uganda', 1);
INSERT INTO Country(country, idContinent) VALUES ('Western Sahara', 1);
INSERT INTO Country(country, idContinent) VALUES ('Zambia', 1);
INSERT INTO Country(country, idContinent) VALUES ('Zimbabwe', 1);
INSERT INTO Country(country, idContinent) VALUES ('Antigua and Barbuda', 5);
INSERT INTO Country(country, idContinent) VALUES ('Aruba', 5);
INSERT INTO Country(country, idContinent) VALUES ('Bahamas', 5);
INSERT INTO Country(country, idContinent) VALUES ('Barbados', 5);
INSERT INTO Country(country, idContinent) VALUES ('Belize', 5);
INSERT INTO Country(country, idContinent) VALUES ('Bermuda', 5);
INSERT INTO Country(country, idContinent) VALUES ('British Virgin Islands', 5);
INSERT INTO Country(country, idContinent) VALUES ('Canada', 5);
INSERT INTO Country(country, idContinent) VALUES ('Cayman Islands', 5);
INSERT INTO Country(country, idContinent) VALUES ('Costa Rica', 5);
INSERT INTO Country(country, idContinent) VALUES ('Cuba', 5);
INSERT INTO Country(country, idContinent) VALUES ('Dominica', 5);
INSERT INTO Country(country, idContinent) VALUES ('Dominican Republic', 5);
INSERT INTO Country(country, idContinent) VALUES ('El Salvador', 5);
INSERT INTO Country(country, idContinent) VALUES ('Greenland', 5);
INSERT INTO Country(country, idContinent) VALUES ('Grenada', 5);
INSERT INTO Country(country, idContinent) VALUES ('Guadeloupe', 5);
INSERT INTO Country(country, idContinent) VALUES ('Guatemala', 5);
INSERT INTO Country(country, idContinent) VALUES ('Haiti', 5);
INSERT INTO Country(country, idContinent) VALUES ('Honduras', 5);
INSERT INTO Country(country, idContinent) VALUES ('Jamaica', 5);
INSERT INTO Country(country, idContinent) VALUES ('Martinique', 5);
INSERT INTO Country(country, idContinent) VALUES ('Mexico', 5);
INSERT INTO Country(country, idContinent) VALUES ('Netherlands Antilles', 5);
INSERT INTO Country(country, idContinent) VALUES ('Nicaragua', 5);
INSERT INTO Country(country, idContinent) VALUES ('Panama', 5);
INSERT INTO Country(country, idContinent) VALUES ('Puerto Rico', 5);
INSERT INTO Country(country, idContinent) VALUES ('Saint Kitts and Nevis', 5);
INSERT INTO Country(country, idContinent) VALUES ('Saint Lucia', 5);
INSERT INTO Country(country, idContinent) VALUES ('Saint Pierre and Miquelon', 5);
INSERT INTO Country(country, idContinent) VALUES ('Saint Vincent and the Grenadines', 5);
INSERT INTO Country(country, idContinent) VALUES ('Trinidad and Tobago', 5);
INSERT INTO Country(country, idContinent) VALUES ('United States', 5);
INSERT INTO Country(country, idContinent) VALUES ('United States Minor Outlying Islands', 5);
INSERT INTO Country(country, idContinent) VALUES ('Argentina', 7);
INSERT INTO Country(country, idContinent) VALUES ('Bolivia', 7);
INSERT INTO Country(country, idContinent) VALUES ('Brazil', 7);
INSERT INTO Country(country, idContinent) VALUES ('Chile', 7);
INSERT INTO Country(country, idContinent) VALUES ('Colombia', 7);
INSERT INTO Country(country, idContinent) VALUES ('Ecuador', 7);
INSERT INTO Country(country, idContinent) VALUES ('Falkland Islands', 7);
INSERT INTO Country(country, idContinent) VALUES ('French Guiana', 7);
INSERT INTO Country(country, idContinent) VALUES ('Guyana', 7);
INSERT INTO Country(country, idContinent) VALUES ('Paraguay', 7);
INSERT INTO Country(country, idContinent) VALUES ('Peru', 7);
INSERT INTO Country(country, idContinent) VALUES ('South Georgia and the South Sandwich Islands', 7);
INSERT INTO Country(country, idContinent) VALUES ('Suriname', 7);
INSERT INTO Country(country, idContinent) VALUES ('Uruguay', 7);
INSERT INTO Country(country, idContinent) VALUES ('Venezuela', 7);
INSERT INTO Country(country, idContinent) VALUES ('Australia', 6);
INSERT INTO Country(country, idContinent) VALUES ('Christmas Island', 6);
INSERT INTO Country(country, idContinent) VALUES ('Cook Islands', 6);
INSERT INTO Country(country, idContinent) VALUES ('East Timor', 6);
INSERT INTO Country(country, idContinent) VALUES ('Fiji', 6);
INSERT INTO Country(country, idContinent) VALUES ('French Polynesia', 6);
INSERT INTO Country(country, idContinent) VALUES ('Kiribati', 6);
INSERT INTO Country(country, idContinent) VALUES ('Marshall Islands', 6);
INSERT INTO Country(country, idContinent) VALUES ('Micronesia', 6);
INSERT INTO Country(country, idContinent) VALUES ('Nauru', 6);
INSERT INTO Country(country, idContinent) VALUES ('New Caledonia', 6);
INSERT INTO Country(country, idContinent) VALUES ('New Zealand', 6);
INSERT INTO Country(country, idContinent) VALUES ('Palau', 6);
INSERT INTO Country(country, idContinent) VALUES ('Papua New Guinea', 6);
INSERT INTO Country(country, idContinent) VALUES ('Samoa', 6);
INSERT INTO Country(country, idContinent) VALUES ('Solomon Islands', 6);
INSERT INTO Country(country, idContinent) VALUES ('Tonga', 6);
INSERT INTO Country(country, idContinent) VALUES ('Tuvalu', 6);
INSERT INTO Country(country, idContinent) VALUES ('Vanuatu', 6);
INSERT INTO Country(country, idContinent) VALUES ('Sin Pais', 2);
